// ─── Types ───────────────────────────────────────────────────────────────────

export interface VocabCard {
  type: 'vocab'
  word: string
  phonetic: string
  pos: string
  meaning: string
  example: string
  options: string[]
  answer: string
}

export interface GrammarCard {
  type: 'grammar'
  rule: string
  explanation: string
  examples: string[]
  tip: string
  question: string
  options: string[]
  answer: string
}

export interface SpeakingCard {
  type: 'speaking'
  prompt: string
  hint: string
  samplePhrases: string[]
}

export type LessonCard = VocabCard | GrammarCard | SpeakingCard

export interface LessonData {
  id: string
  stageId: string
  title: string
  type: 'vocabulary' | 'grammar' | 'speaking'
  topic: string
  level: 'A1' | 'A2' | 'B1' | 'B2'
  description: string
  xp: number
  cards: LessonCard[]
}

export interface StageData {
  id: string
  title: string
  subtitle: string
  icon: string
  color: string
  accentColor: string
  lessons: LessonData[]
}

// ─── Lesson Data ─────────────────────────────────────────────────────────────

export const STAGES: StageData[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // STAGE 1 — Nền tảng (A1)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'stage-1',
    title: 'Stage 1',
    subtitle: 'Nền tảng',
    icon: '🌱',
    color: 'from-emerald-500 to-cyan-500',
    accentColor: 'emerald',
    lessons: [
      {
        id: 'l1',
        stageId: 'stage-1',
        title: 'Từ vựng cá nhân & Nghề nghiệp',
        type: 'vocabulary',
        topic: 'Personal Info',
        level: 'A1',
        description: 'Từ vựng thiết yếu để nói về bản thân, nghề nghiệp và mục tiêu — nền tảng IELTS Part 1',
        xp: 60,
        cards: [
          {
            type: 'vocab',
            word: 'profession',
            phonetic: '/prəˈfeʃ.ən/',
            pos: 'n.',
            meaning: 'Nghề nghiệp (có trình độ chuyên môn)',
            example: 'Teaching is a profession that requires both knowledge and patience.',
            options: ['Sở thích cá nhân', 'Nghề nghiệp chuyên môn', 'Bằng cấp, học vị', 'Kỹ năng mềm'],
            answer: 'Nghề nghiệp chuyên môn',
          },
          {
            type: 'vocab',
            word: 'aspiration',
            phonetic: '/ˌæs.pɪˈreɪ.ʃən/',
            pos: 'n.',
            meaning: 'Khát vọng, hoài bão',
            example: 'My greatest aspiration is to work as an environmental researcher.',
            options: ['Thành tích đã đạt được', 'Khó khăn, thử thách', 'Khát vọng, hoài bão', 'Kinh nghiệm làm việc'],
            answer: 'Khát vọng, hoài bão',
          },
          {
            type: 'vocab',
            word: 'confident',
            phonetic: '/ˈkɒn.fɪ.dənt/',
            pos: 'adj.',
            meaning: 'Tự tin',
            example: 'Being confident in speaking English takes consistent practice every day.',
            options: ['Lo lắng, hồi hộp', 'Tự tin', 'Nhút nhát, rụt rè', 'Kiên nhẫn, bình tĩnh'],
            answer: 'Tự tin',
          },
          {
            type: 'vocab',
            word: 'background',
            phonetic: '/ˈbæk.ɡraʊnd/',
            pos: 'n.',
            meaning: 'Xuất thân, lý lịch',
            example: 'She comes from a background in science, so she chose to study medicine.',
            options: ['Xuất thân, lý lịch', 'Tính cách, cá tính', 'Thành tích học tập', 'Mục tiêu tương lai'],
            answer: 'Xuất thân, lý lịch',
          },
          {
            type: 'vocab',
            word: 'pursue',
            phonetic: '/pəˈsjuː/',
            pos: 'v.',
            meaning: 'Theo đuổi (mục tiêu, ước mơ)',
            example: 'He decided to pursue a career in engineering after graduating.',
            options: ['Từ bỏ, bỏ cuộc', 'Theo đuổi, phấn đấu', 'Đạt được, giành được', 'Trì hoãn, hoãn lại'],
            answer: 'Theo đuổi, phấn đấu',
          },
          {
            type: 'vocab',
            word: 'achievement',
            phonetic: '/əˈtʃiːv.mənt/',
            pos: 'n.',
            meaning: 'Thành tích, thành tựu',
            example: 'Winning the national English competition was her greatest achievement.',
            options: ['Thất bại, vấp ngã', 'Thử thách, khó khăn', 'Thành tích, thành tựu', 'Kế hoạch, dự định'],
            answer: 'Thành tích, thành tựu',
          },
          {
            type: 'vocab',
            word: 'fluent',
            phonetic: '/ˈfluː.ənt/',
            pos: 'adj.',
            meaning: 'Lưu loát, thành thạo',
            example: 'She is fluent in three languages — Vietnamese, English, and French.',
            options: ['Cơ bản, sơ cấp', 'Lưu loát, thành thạo', 'Vấp váp, thiếu tự nhiên', 'Chính xác, không lỗi'],
            answer: 'Lưu loát, thành thạo',
          },
          {
            type: 'vocab',
            word: 'motivated',
            phonetic: '/ˈməʊ.tɪ.veɪ.tɪd/',
            pos: 'adj.',
            meaning: 'Có động lực, hăng hái',
            example: 'I feel highly motivated when I see real progress in my English skills.',
            options: ['Mệt mỏi, kiệt sức', 'Chán nản, thất vọng', 'Có động lực, hăng hái', 'Lo lắng, bất an'],
            answer: 'Có động lực, hăng hái',
          },
        ] as LessonCard[],
      },

      {
        id: 'l2',
        stageId: 'stage-1',
        title: 'Thì Hiện Tại Đơn',
        type: 'grammar',
        topic: 'Simple Present',
        level: 'A1',
        description: 'Nắm vững cấu trúc thì hiện tại đơn — công cụ cốt lõi cho mọi câu trả lời IELTS Part 1',
        xp: 60,
        cards: [
          {
            type: 'grammar',
            rule: 'Cấu trúc cơ bản',
            explanation: 'Thì Hiện Tại Đơn diễn tả thói quen, sự thật chung và trạng thái ổn định. Công thức: I/You/We/They + V nguyên mẫu · He/She/It + V + s/es. Dùng nhiều trong IELTS Part 1 khi nói về bản thân.',
            examples: [
              'I study at Ho Chi Minh City University of Technology.',
              'She works as a nurse at a local hospital.',
              'They live together in a small apartment near the centre.',
            ],
            tip: 'Dấu hiệu nhận biết: every day, usually, always, often, sometimes, never, on weekdays',
            question: 'My sister ___ (work) as a software engineer at a tech company.',
            options: ['work', 'works', 'worked', 'is working'],
            answer: 'works',
          },
          {
            type: 'grammar',
            rule: 'Quy tắc thêm -s/-es/-ies (ngôi 3 số ít)',
            explanation: 'Động từ kết thúc bằng -s/-x/-ch/-sh/-o → thêm -es. Kết thúc phụ âm + y → bỏ y, thêm -ies. Còn lại → thêm -s thông thường. Đặc biệt: go→goes, do→does, have→has.',
            examples: [
              'watch → watches | He watches the news every morning.',
              'study → studies | She studies English for two hours daily.',
              'play → plays | He plays guitar in a band on weekends.',
              'go → goes | She goes to the gym before work.',
            ],
            tip: 'go→goes, do→does, have→has là 3 trường hợp đặc biệt phải nhớ',
            question: 'He ___ (do) yoga every morning to stay healthy and focused.',
            options: ['do', 'dos', 'does', 'doing'],
            answer: 'does',
          },
          {
            type: 'grammar',
            rule: 'Phủ định: don\'t / doesn\'t',
            explanation: 'Phủ định: I/You/We/They + do not (don\'t) + V. He/She/It + does not (doesn\'t) + V. Quan trọng: sau doesn\'t luôn dùng V nguyên mẫu — không thêm -s!',
            examples: [
              'I don\'t drink coffee — I prefer green tea.',
              'She doesn\'t eat meat because she\'s been vegetarian for years.',
              'My parents don\'t use social media very much.',
            ],
            tip: 'Lỗi thường gặp: "She doesn\'t likes" là SAI. Đúng: "She doesn\'t like" (V nguyên mẫu)',
            question: 'He ___ enjoy watching TV — he prefers reading books instead.',
            options: ["don't enjoy", "doesn't enjoy", "isn't enjoy", "not enjoys"],
            answer: "doesn't enjoy",
          },
          {
            type: 'grammar',
            rule: 'Câu hỏi: Do / Does',
            explanation: 'Câu hỏi Yes/No: Do + I/you/we/they + V? / Does + he/she/it + V? Trả lời: Yes, she does. / No, I don\'t. Câu hỏi Wh-: What/Where/Why + do/does + S + V?',
            examples: [
              'Do you live near your workplace?',
              'Does she speak any other languages besides English?',
              'What do you enjoy doing in your free time?',
              'Where does your family live?',
            ],
            tip: 'V trong câu hỏi luôn là nguyên mẫu dù dùng "does": Does she like? (NOT Does she likes?)',
            question: '___ your brother study engineering or business at university?',
            options: ['Do', 'Does', 'Is', 'Has'],
            answer: 'Does',
          },
          {
            type: 'grammar',
            rule: 'Trạng từ tần suất',
            explanation: 'Trạng từ tần suất đứng TRƯỚC động từ thường, SAU động từ "to be". Thứ tự: always (100%) → usually (80%) → often (60%) → sometimes (40%) → rarely (20%) → never (0%).',
            examples: [
              'I usually wake up at 6am on weekdays. (trước V thường)',
              'She is always on time for her IELTS classes. (sau be)',
              'They rarely eat fast food — they cook at home instead.',
            ],
            tip: 'Nhớ công thức: Subject + [adverb] + Verb thường / Subject + be + [adverb]',
            question: 'She ___ listens to English podcasts during her morning commute.',
            options: ['always listens to English → always', 'usually', 'often often', 'always'],
            answer: 'always',
          },
          {
            type: 'grammar',
            rule: 'Ứng dụng trong IELTS Part 1',
            explanation: 'Thì Hiện Tại Đơn là thì chính trong IELTS Part 1. Dùng để mô tả thói quen, sở thích, và cuộc sống hằng ngày. Kết hợp với trạng từ tần suất và chi tiết cụ thể để câu trả lời hay hơn.',
            examples: [
              'I work as a... and I usually start my day by... — (Band 6)',
              'I\'m currently studying... and I generally spend... hours a day... — (Band 7)',
              'I tend to... which I find particularly... because... — (Band 8)',
            ],
            tip: 'Thêm "because / which / since" để giải thích → tăng điểm Coherence & Lexical Resource',
            question: 'Câu nào diễn đạt thói quen ở Band 7+ trong IELTS Part 1?',
            options: [
              'I like reading.',
              'I often read books.',
              'I tend to read non-fiction books, which I find really thought-provoking.',
              'I read books every day always.',
            ],
            answer: 'I tend to read non-fiction books, which I find really thought-provoking.',
          },
        ] as LessonCard[],
      },

      {
        id: 'l3',
        stageId: 'stage-1',
        title: 'IELTS Part 1: Về bản thân',
        type: 'speaking',
        topic: 'About Yourself',
        level: 'A1',
        description: 'Luyện tập trả lời câu hỏi IELTS Part 1 về bản thân — phần thi đầu tiên và quan trọng nhất',
        xp: 100,
        cards: [
          {
            type: 'speaking',
            prompt: "Let's talk about where you live. Can you describe your hometown or the city you live in?",
            hint: 'Nói tên thành phố, vị trí địa lý, điểm nổi bật. Thêm cảm nhận cá nhân về nơi đó để câu trả lời sinh động hơn.',
            samplePhrases: [
              'I live in [city], which is located in the [north/south/central] of Vietnam.',
              'It\'s quite a [bustling/peaceful/modern] city with a population of around...',
              'What I love most about living here is...',
              'One downside is that it can get very [crowded/hot/expensive], but overall...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'What do you do? Are you working or studying at the moment?',
            hint: 'Nêu công việc/ngành học, trường/công ty, và lý do bạn chọn. Tránh câu trả lời quá ngắn — thêm ít nhất 1 chi tiết.',
            samplePhrases: [
              'I\'m currently in my [second/third] year studying [major] at [university].',
              'I work as a [job title] at a [type of company], and I\'ve been doing this for [time].',
              'I chose this field because I\'ve always been passionate about...',
              'My work involves [description of duties], which I find really [adjective].',
            ],
          },
          {
            type: 'speaking',
            prompt: 'What do you enjoy doing in your free time? Do you have any hobbies?',
            hint: 'Đề cập 2 sở thích, giải thích tại sao thích và khi nào bạn làm. Thêm "particularly" hoặc "especially" để nâng band.',
            samplePhrases: [
              'In my free time, I particularly enjoy..., which I find really [relaxing/stimulating/creative].',
              'I\'ve been into... for about [time] now, and I try to... at least [frequency].',
              'I also like..., especially when I want to [unwind/challenge myself/socialise].',
              'I suppose my main hobby would be..., because it allows me to...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Do you prefer spending time alone or with other people? Why?',
            hint: 'Nêu rõ lập trường (thích một mình / thích có bạn bè / tuỳ tình huống), sau đó giải thích với ví dụ cụ thể.',
            samplePhrases: [
              'I\'d say I\'m more of an introvert/extrovert, so I tend to...',
              'It really depends on the situation — when I need to recharge, I...',
              'I genuinely enjoy spending time with friends because...',
              'That said, I also value my alone time, particularly when I want to...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'What are your plans or goals for the future?',
            hint: 'Nói về kế hoạch ngắn hạn (1-2 năm) và dài hạn. Dùng: I\'m planning to / I hope to / My goal is to / I\'d like to.',
            samplePhrases: [
              'In the short term, I\'m planning to [specific goal] within the next [time].',
              'Ultimately, I\'d like to [long-term aspiration] because...',
              'I\'m also hoping to improve my [skill], which I think will help me...',
              'One of my main goals is to... so I\'ve been [action] to work towards that.',
            ],
          },
        ] as LessonCard[],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // STAGE 2 — Gia đình & Bạn bè (A2)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'stage-2',
    title: 'Stage 2',
    subtitle: 'Gia đình & Bạn bè',
    icon: '👨‍👩‍👧',
    color: 'from-cyan-500 to-blue-500',
    accentColor: 'cyan',
    lessons: [
      {
        id: 'l4',
        stageId: 'stage-2',
        title: 'Từ vựng Gia đình & Mối quan hệ',
        type: 'vocabulary',
        topic: 'Family & Relationships',
        level: 'A2',
        description: 'Từ vựng phong phú để mô tả gia đình và mối quan hệ — chủ đề phổ biến trong IELTS Part 1 & 2',
        xp: 70,
        cards: [
          {
            type: 'vocab',
            word: 'upbringing',
            phonetic: '/ˈʌp.brɪŋ.ɪŋ/',
            pos: 'n.',
            meaning: 'Cách nuôi dạy, môi trường lớn lên',
            example: 'Her upbringing in a strict household taught her the value of discipline.',
            options: ['Tuổi thơ vui vẻ', 'Cách nuôi dạy, môi trường lớn lên', 'Truyền thống gia đình', 'Mối quan hệ gia đình'],
            answer: 'Cách nuôi dạy, môi trường lớn lên',
          },
          {
            type: 'vocab',
            word: 'bond',
            phonetic: '/bɒnd/',
            pos: 'n.',
            meaning: 'Mối gắn kết tình cảm',
            example: 'The bond between my mother and I has grown stronger as I\'ve gotten older.',
            options: ['Mâu thuẫn, xung đột', 'Khoảng cách, rào cản', 'Mối gắn kết tình cảm', 'Quy tắc, kỷ luật'],
            answer: 'Mối gắn kết tình cảm',
          },
          {
            type: 'vocab',
            word: 'supportive',
            phonetic: '/səˈpɔː.tɪv/',
            pos: 'adj.',
            meaning: 'Hỗ trợ, ủng hộ, chỗ dựa vững chắc',
            example: 'My family is incredibly supportive of my decision to study abroad.',
            options: ['Nghiêm khắc, đòi hỏi cao', 'Lạnh lùng, xa cách', 'Hỗ trợ, ủng hộ, chỗ dựa', 'Bảo thủ, cứng nhắc'],
            answer: 'Hỗ trợ, ủng hộ, chỗ dựa',
          },
          {
            type: 'vocab',
            word: 'generation',
            phonetic: '/ˌdʒen.əˈreɪ.ʃən/',
            pos: 'n.',
            meaning: 'Thế hệ',
            example: 'There\'s often a generation gap between parents and teenagers on lifestyle choices.',
            options: ['Thế kỷ, trăm năm', 'Thế hệ', 'Thập kỷ, mười năm', 'Thời đại, kỷ nguyên'],
            answer: 'Thế hệ',
          },
          {
            type: 'vocab',
            word: 'nurture',
            phonetic: '/ˈnɜː.tʃər/',
            pos: 'v.',
            meaning: 'Nuôi dưỡng, vun đắp (tình cảm, tài năng)',
            example: 'Good parents nurture their children\'s talents and encourage their passions.',
            options: ['Nuôi dưỡng, vun đắp', 'Kiểm soát, giám sát', 'Phê bình, chỉ trích', 'Bỏ mặc, thiếu quan tâm'],
            answer: 'Nuôi dưỡng, vun đắp',
          },
          {
            type: 'vocab',
            word: 'close-knit',
            phonetic: '/ˌkləʊsˈnɪt/',
            pos: 'adj.',
            meaning: 'Gắn bó, đoàn kết (gia đình, cộng đồng)',
            example: 'We are a very close-knit family — we have dinner together every Sunday without fail.',
            options: ['Lạnh nhạt, thiếu giao tiếp', 'Bận rộn, ít gặp mặt', 'Đông người, phức tạp', 'Gắn bó, đoàn kết'],
            answer: 'Gắn bó, đoàn kết',
          },
          {
            type: 'vocab',
            word: 'influence',
            phonetic: '/ˈɪn.flu.əns/',
            pos: 'n./v.',
            meaning: 'Ảnh hưởng; tác động',
            example: 'My father has had the greatest influence on my career choices and values.',
            options: ['Hạn chế, cản trở', 'Ảnh hưởng, tác động', 'Quyết định thay cho', 'Áp lực, ép buộc'],
            answer: 'Ảnh hưởng, tác động',
          },
          {
            type: 'vocab',
            word: 'extended family',
            phonetic: '/ɪkˌsten.dɪd ˈfæm.ə.li/',
            pos: 'n. phrase',
            meaning: 'Đại gia đình (bao gồm ông bà, cô chú, họ hàng)',
            example: 'In Vietnam, it\'s common to live with your extended family under one roof.',
            options: ['Gia đình hạt nhân (bố mẹ con)', 'Gia đình đơn thân', 'Đại gia đình (họ hàng)', 'Gia đình nuôi dưỡng'],
            answer: 'Đại gia đình (họ hàng)',
          },
        ] as LessonCard[],
      },

      {
        id: 'l5',
        stageId: 'stage-2',
        title: 'Thì Hiện Tại Tiếp Diễn',
        type: 'grammar',
        topic: 'Present Continuous',
        level: 'A2',
        description: 'Dùng thì HTTD để nói về hành động đang xảy ra và kế hoạch đã sắp xếp — thiết yếu trong IELTS',
        xp: 70,
        cards: [
          {
            type: 'grammar',
            rule: 'Cấu trúc & công dụng chính',
            explanation: 'Thì Hiện Tại Tiếp Diễn: S + am/is/are + V-ing. Dùng khi: (1) Hành động đang xảy ra ngay lúc nói, (2) Tình huống đang thay đổi, (3) Kế hoạch đã sắp xếp cho tương lai gần.',
            examples: [
              'I\'m studying for my IELTS exam this week. (đang trong quá trình)',
              'More and more people are learning English online. (xu hướng đang thay đổi)',
              'We\'re meeting the examiner tomorrow at 9am. (kế hoạch đã xếp)',
            ],
            tip: 'Dấu hiệu: now, right now, at the moment, currently, this week/month, look!, listen!',
            question: 'The number of people learning English online ___ rapidly these days.',
            options: ['grow', 'grows', 'is growing', 'grew'],
            answer: 'is growing',
          },
          {
            type: 'grammar',
            rule: 'Quy tắc thêm -ing',
            explanation: 'Động từ kết thúc bằng -e câm → bỏ e + ing (write→writing). Kết thúc CVC ngắn → nhân đôi phụ âm cuối (run→running, sit→sitting). Trường hợp khác → thêm -ing bình thường.',
            examples: [
              'make → making | take → taking (bỏ -e)',
              'run → running | swim → swimming (nhân đôi)',
              'play → playing | read → reading (thêm -ing bình thường)',
              'lie → lying (ie→y+ing)',
            ],
            tip: 'Không nhân đôi nếu kết thúc -w/-x/-y: mix→mixing, snow→snowing, enjoy→enjoying',
            question: 'She ___ (sit) in the café and reviewing her IELTS notes right now.',
            options: ['is sitting', 'is siting', 'is sitten', 'sits'],
            answer: 'is sitting',
          },
          {
            type: 'grammar',
            rule: 'Stative verbs — KHÔNG dùng -ing',
            explanation: 'Động từ trạng thái không được dùng với thì tiếp diễn: THINK (think, believe, know, understand), FEEL (like, love, hate, prefer), HAVE (own, possess), SENSE (see, hear, smell, taste, seem).',
            examples: [
              '✓ I know the answer. ✗ I am knowing the answer.',
              '✓ She loves her family. ✗ She is loving her family.',
              '✓ He seems tired. ✗ He is seeming tired.',
              '⚠ "I\'m thinking about you" = OK (think = đang suy nghĩ, không phải ý kiến)',
            ],
            tip: '"think" có 2 nghĩa: "believe" (stative) vs "consider/ponder" (action) — ngữ cảnh quyết định',
            question: 'She ___ exactly what the examiner wants in a Band 7 answer.',
            options: ['is knowing', 'know', 'knows', 'is know'],
            answer: 'knows',
          },
          {
            type: 'grammar',
            rule: 'HTTD cho tương lai (kế hoạch đã xếp)',
            explanation: 'HTTD + trạng từ tương lai = kế hoạch đã được xác nhận/sắp xếp cụ thể. Khác với "going to" (ý định) và "will" (quyết định tại chỗ).',
            examples: [
              'I\'m flying to Hanoi next Monday — I\'ve already bought the tickets.',
              'She\'s starting her new job next week. Everything is arranged.',
              'We\'re having a family reunion this Sunday — we booked the restaurant yesterday.',
            ],
            tip: 'Đã book/sắp xếp → HTTD. Ý định chưa chắc → going to. Quyết định ngay lúc đó → will',
            question: 'I ___ (meet) my IELTS tutor on Friday afternoon — it\'s already booked.',
            options: ['will meet', 'meet', 'am meeting', 'going to meet'],
            answer: 'am meeting',
          },
          {
            type: 'grammar',
            rule: 'HTTĐ vs HTTD — Phân biệt',
            explanation: 'HTTĐ: thói quen, sự thật chung, cảm xúc. HTTD: hành động tạm thời, đang xảy ra, xu hướng đang thay đổi. Cùng một động từ nhưng nghĩa hoàn toàn khác.',
            examples: [
              'I walk to school every day. (thói quen — HTTĐ)',
              'I\'m walking to school right now. (đang đi — HTTD)',
              'She usually cooks dinner. (thói quen)',
              'She\'s cooking something special tonight. (tạm thời)',
            ],
            tip: 'Every day/usually → HTTĐ | Right now/this week/currently → HTTD',
            question: 'Look! The children ___ (play) in the garden. It\'s so cute to watch.',
            options: ['play', 'plays', 'are playing', 'have played'],
            answer: 'are playing',
          },
        ] as LessonCard[],
      },

      {
        id: 'l6',
        stageId: 'stage-2',
        title: 'IELTS Part 1: Gia đình & Bạn bè',
        type: 'speaking',
        topic: 'Family & Friends',
        level: 'A2',
        description: 'Luyện trả lời câu hỏi IELTS Part 1 về gia đình — một trong những chủ đề xuất hiện nhiều nhất',
        xp: 100,
        cards: [
          {
            type: 'speaking',
            prompt: 'Do you have a large or small family? Tell me about your family members.',
            hint: 'Nêu số lượng thành viên, mô tả từng người (quan hệ, nghề nghiệp, tính cách). Tránh chỉ liệt kê — hãy thêm tính từ mô tả.',
            samplePhrases: [
              'I come from a [small/medium-sized/large] family of [number] people.',
              'My [mother/father] is a [profession] and she/he is known for being very [adjective].',
              'My [sibling] and I are very close — we share a lot of interests, including...',
              'We\'re a pretty close-knit family, so we make an effort to...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'How much time do you spend with your family? Do you think this is enough?',
            hint: 'Mô tả tần suất gặp mặt, các hoạt động chung, và cảm nhận của bạn. Thêm nguyên nhân nếu ít gặp (bận rộn, sống xa...).',
            samplePhrases: [
              'We try to have dinner together at least [frequency], which I think is really valuable.',
              'To be honest, I don\'t spend as much time with my family as I\'d like, mainly because...',
              'Whenever we get together, we usually... which really helps us stay connected.',
              'I believe quality time matters more than quantity, so even when we\'re busy...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Who in your family has had the greatest influence on you? Why?',
            hint: 'Chọn một người cụ thể, giải thích họ ảnh hưởng đến bạn theo cách nào (giá trị sống, sự nghiệp, tính cách). Dùng ví dụ cụ thể.',
            samplePhrases: [
              'Without a doubt, my [family member] has had the greatest influence on who I am today.',
              'She/He taught me the value of [quality] by [specific example].',
              'Growing up, I watched my [family member]... and that really shaped my attitude towards...',
              'I suppose the biggest lesson I\'ve learned from them is that...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Do you think family relationships in Vietnam are changing? In what ways?',
            hint: 'Đây là câu hỏi Part 1 nâng cao — so sánh quá khứ và hiện tại. Nêu 1-2 thay đổi cụ thể với ví dụ.',
            samplePhrases: [
              'I think family dynamics in Vietnam are definitely shifting, particularly in urban areas.',
              'In the past, it was common for... but nowadays, more and more families...',
              'One noticeable change is that... which I think is partly due to...',
              'That said, many core values like respect for elders still remain very strong.',
            ],
          },
        ] as LessonCard[],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // STAGE 3 — Học tập & Sự nghiệp (A2)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'stage-3',
    title: 'Stage 3',
    subtitle: 'Học tập & Sự nghiệp',
    icon: '💼',
    color: 'from-violet-500 to-pink-500',
    accentColor: 'violet',
    lessons: [
      {
        id: 'l7',
        stageId: 'stage-3',
        title: 'Từ vựng Giáo dục & Sự nghiệp',
        type: 'vocabulary',
        topic: 'Education & Career',
        level: 'A2',
        description: 'Từ vựng học thuật và nghề nghiệp cần thiết cho IELTS Part 1, 2 và cả Writing Task 2',
        xp: 80,
        cards: [
          {
            type: 'vocab',
            word: 'curriculum',
            phonetic: '/kəˈrɪk.jʊ.ləm/',
            pos: 'n.',
            meaning: 'Chương trình giảng dạy',
            example: 'The university curriculum includes both theory and practical training sessions.',
            options: ['Phương pháp học tập', 'Chương trình giảng dạy', 'Bằng cấp, chứng chỉ', 'Học phí, chi phí'],
            answer: 'Chương trình giảng dạy',
          },
          {
            type: 'vocab',
            word: 'scholarship',
            phonetic: '/ˈskɒl.ə.ʃɪp/',
            pos: 'n.',
            meaning: 'Học bổng',
            example: 'She received a full scholarship to study abroad, covering all her tuition fees.',
            options: ['Học bổng', 'Khoản vay sinh viên', 'Trợ cấp sinh hoạt', 'Phần thưởng học tập'],
            answer: 'Học bổng',
          },
          {
            type: 'vocab',
            word: 'internship',
            phonetic: '/ˈɪn.tɜːn.ʃɪp/',
            pos: 'n.',
            meaning: 'Thực tập (trong doanh nghiệp/tổ chức)',
            example: 'I completed a six-month internship at a marketing agency during my final year.',
            options: ['Kỳ thi tốt nghiệp', 'Thực tập chuyên ngành', 'Hội thảo, seminar', 'Dự án nhóm'],
            answer: 'Thực tập chuyên ngành',
          },
          {
            type: 'vocab',
            word: 'specialize',
            phonetic: '/ˈspeʃ.ə.laɪz/',
            pos: 'v.',
            meaning: 'Chuyên về, chuyên sâu vào',
            example: 'She decided to specialize in environmental engineering after her first internship.',
            options: ['Thay đổi chuyên ngành', 'Chuyên về, chuyên sâu vào', 'Học nhiều môn khác nhau', 'Bỏ học giữa chừng'],
            answer: 'Chuyên về, chuyên sâu vào',
          },
          {
            type: 'vocab',
            word: 'qualification',
            phonetic: '/ˌkwɒl.ɪ.fɪˈkeɪ.ʃən/',
            pos: 'n.',
            meaning: 'Bằng cấp, chứng chỉ, tiêu chuẩn',
            example: 'Having international qualifications significantly improves your career prospects.',
            options: ['Kinh nghiệm làm việc', 'Bằng cấp, chứng chỉ', 'Kỹ năng cá nhân', 'Mạng lưới quan hệ'],
            answer: 'Bằng cấp, chứng chỉ',
          },
          {
            type: 'vocab',
            word: 'competitive',
            phonetic: '/kəmˈpet.ɪ.tɪv/',
            pos: 'adj.',
            meaning: 'Cạnh tranh, ganh đua cao',
            example: 'The job market for engineers is extremely competitive, with hundreds applying per vacancy.',
            options: ['Dễ dàng, ít cạnh tranh', 'Cạnh tranh, ganh đua cao', 'Công bằng, minh bạch', 'Phức tạp, khó hiểu'],
            answer: 'Cạnh tranh, ganh đua cao',
          },
          {
            type: 'vocab',
            word: 'mentor',
            phonetic: '/ˈmen.tɔːr/',
            pos: 'n.',
            meaning: 'Người hướng dẫn, thầy/cô đỡ đầu',
            example: 'My professor became my mentor and helped me secure my first research position.',
            options: ['Người hướng dẫn, đỡ đầu', 'Người phê bình, giám sát', 'Bạn học, đồng môn', 'Đối thủ cạnh tranh'],
            answer: 'Người hướng dẫn, đỡ đầu',
          },
          {
            type: 'vocab',
            word: 'discipline',
            phonetic: '/ˈdɪs.ɪ.plɪn/',
            pos: 'n.',
            meaning: 'Kỷ luật; lĩnh vực học thuật',
            example: 'Success in any discipline requires consistent effort and a strong work ethic.',
            options: ['Kỷ luật; lĩnh vực học thuật', 'Điểm số, kết quả học tập', 'Phần thưởng, công nhận', 'Thất bại, vấp ngã'],
            answer: 'Kỷ luật; lĩnh vực học thuật',
          },
        ] as LessonCard[],
      },

      {
        id: 'l8',
        stageId: 'stage-3',
        title: 'Thì Quá Khứ Đơn',
        type: 'grammar',
        topic: 'Past Simple',
        level: 'A2',
        description: 'Dùng thì quá khứ đơn để kể chuyện và mô tả kinh nghiệm — cốt lõi của IELTS Part 2 cue card',
        xp: 80,
        cards: [
          {
            type: 'grammar',
            rule: 'Cấu trúc & công dụng',
            explanation: 'Thì Quá Khứ Đơn: S + V-ed (regular) / V2 (irregular). Dùng để: mô tả hành động hoàn thành trong quá khứ, kể chuyện theo thứ tự thời gian, nói về kinh nghiệm đã qua.',
            examples: [
              'I studied at Hanoi University from 2018 to 2022.',
              'She moved to Ho Chi Minh City when she was 18.',
              'He won a scholarship and went to Australia last year.',
            ],
            tip: 'Dấu hiệu: yesterday, last week/year, in 2020, ago, when I was..., after/before + clause',
            question: 'I ___ (decide) to pursue engineering after attending an open day at university.',
            options: ['decide', 'decided', 'have decided', 'was deciding'],
            answer: 'decided',
          },
          {
            type: 'grammar',
            rule: 'Động từ bất quy tắc (Irregular verbs)',
            explanation: 'Nhiều động từ phổ biến không tuân theo quy tắc thêm -ed. Phải học thuộc. Nhóm quan trọng nhất cho IELTS Speaking Part 2.',
            examples: [
              'go → went | I went on a trip with my family when I was 15.',
              'meet → met | I met my best friend on the first day of university.',
              'feel → felt | I felt incredibly proud when I passed my exam.',
              'give → gave | My teacher gave me advice that changed my perspective.',
              'become → became | She became passionate about medicine after visiting a hospital.',
            ],
            tip: 'Học theo nhóm: come→came, run→ran, drink→drank, ring→rang (vần với nhau dễ nhớ)',
            question: 'Last summer, she ___ (spend) three weeks volunteering at a local orphanage.',
            options: ['spend', 'spended', 'spent', 'has spent'],
            answer: 'spent',
          },
          {
            type: 'grammar',
            rule: 'Phủ định & Câu hỏi QKĐ',
            explanation: 'Phủ định: S + did not (didn\'t) + V nguyên mẫu. Câu hỏi: Did + S + V nguyên mẫu? Lưu ý: sau did/didn\'t luôn dùng V nguyên mẫu, dù là ngôi 3 số ít.',
            examples: [
              'I didn\'t enjoy my first internship — it wasn\'t what I expected.',
              'She didn\'t pass the exam on her first attempt, but she kept trying.',
              'Did you study abroad at any point during your degree?',
              'What did you find most challenging about your studies?',
            ],
            tip: 'Lỗi phổ biến: "She didn\'t went" là SAI. Đúng: "She didn\'t go" (V nguyên mẫu sau didn\'t)',
            question: '___ you enjoy your work experience at the company last summer?',
            options: ['Do', 'Did', 'Were', 'Have'],
            answer: 'Did',
          },
          {
            type: 'grammar',
            rule: 'QKĐ vs Quá Khứ Tiếp Diễn (was/were + V-ing)',
            explanation: 'QKĐ: hành động hoàn thành, ngắn. QKTD: hành động đang diễn ra (nền). Thường kết hợp: "was doing... when something happened" hoặc "while I was doing..., I noticed..."',
            examples: [
              'I was studying in the library when my phone rang. (QKTD + QKĐ)',
              'While she was presenting her project, she realized she had forgotten a key point.',
              'What were you doing at this time last year?',
            ],
            tip: '"When + QKĐ" = hành động xảy ra đột ngột. "While + QKTD" = hành động đang diễn ra',
            question: 'I ___ (give) a presentation when the fire alarm suddenly went off.',
            options: ['gave', 'was giving', 'have given', 'give'],
            answer: 'was giving',
          },
          {
            type: 'grammar',
            rule: 'Kể chuyện trong IELTS Part 2',
            explanation: 'IELTS Part 2 (cue card) yêu cầu kể một câu chuyện/kinh nghiệm. Dùng QKĐ làm nền tảng, QKTD để tạo bối cảnh, và kết nối bằng linking words.',
            examples: [
              'Set the scene: "It was a sunny afternoon in March 2022 and I was..."',
              'Main event: "Suddenly/Then/After that, I decided to..."',
              'Feelings: "I felt both nervous and excited because..."',
              'Reflection: "Looking back, I realise that this experience taught me..."',
            ],
            tip: 'Công thức Part 2: Bối cảnh → Sự kiện chính → Cảm xúc → Bài học/Ý nghĩa',
            question: 'Câu nào tốt nhất để mở đầu một câu chuyện trong IELTS Part 2?',
            options: [
              'It was good experience.',
              'I went to a place and it was nice.',
              'I\'d like to talk about a memorable trip I took with my family two years ago.',
              'This is about something that happened.',
            ],
            answer: 'I\'d like to talk about a memorable trip I took with my family two years ago.',
          },
        ] as LessonCard[],
      },

      {
        id: 'l9',
        stageId: 'stage-3',
        title: 'IELTS Part 1: Học tập & Nghề nghiệp',
        type: 'speaking',
        topic: 'Work & Study',
        level: 'A2',
        description: 'Thực hành trả lời câu hỏi IELTS Part 1 về công việc, ngành học — chủ đề trong mọi đề thi',
        xp: 110,
        cards: [
          {
            type: 'speaking',
            prompt: 'What subject are you studying? Why did you choose it?',
            hint: 'Nêu ngành học, trường, lý do chọn (đam mê, triển vọng nghề nghiệp, ảnh hưởng của ai đó). Câu trả lời nên 40-60 giây.',
            samplePhrases: [
              'I\'m currently studying [subject] at [university name], and I\'m in my [year] year.',
              'I chose this field because I\'ve always been fascinated by... ever since I was young.',
              'I was also drawn to it because of the career opportunities, particularly in...',
              'Honestly, my [teacher/family member] inspired me to pursue this path when...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'What aspects of your work/studies do you enjoy the most?',
            hint: 'Nêu 1-2 điều cụ thể bạn thích nhất và giải thích tại sao. Dùng: particularly, especially, what I love most is...',
            samplePhrases: [
              'What I enjoy most is... because it allows me to be creative and think critically.',
              'I particularly like the [practical/theoretical/collaborative] aspects of my work.',
              'The most rewarding part is when I can see the real-world impact of what I do.',
              'I also really appreciate that my [studies/job] constantly challenges me to...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Is there anything you find difficult or challenging about your studies or job?',
            hint: 'Thành thật nhưng chuyên nghiệp — nêu thách thức thực sự và cách bạn xử lý/học hỏi từ đó.',
            samplePhrases: [
              'I won\'t pretend it\'s always easy — I sometimes struggle with...',
              'The most challenging aspect is probably..., but I\'ve learned to manage it by...',
              'There are times when I feel overwhelmed by the workload, especially when...',
              'I\'ve come to see these challenges as opportunities to grow rather than...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Do you have a dream job? What kind of work would you ideally like to do?',
            hint: 'Mô tả công việc lý tưởng — môi trường, trách nhiệm, lý do hấp dẫn. Nếu đã làm công việc mơ ước, nói về điều bạn muốn phát triển tiếp.',
            samplePhrases: [
              'My dream has always been to work in [field], specifically in [role] because...',
              'Ideally, I\'d love to work in an environment that is [creative/collaborative/impactful].',
              'I\'m drawn to [type of work] because it combines my passion for [A] with my skills in [B].',
              'More than anything, I want a career that makes a positive difference, such as...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Do you think work-life balance is important? How do you maintain yours?',
            hint: 'Đây là câu hỏi ý kiến kết hợp kinh nghiệm cá nhân. Trả lời: lập trường → lý do → kinh nghiệm/ví dụ cụ thể.',
            samplePhrases: [
              'Absolutely — I think maintaining a healthy balance is essential for both productivity and wellbeing.',
              'Personally, I try to... to make sure I don\'t let work take over my whole life.',
              'There are definitely times when I struggle to switch off, particularly when...',
              'I\'ve found that [specific habit, e.g., having a regular exercise routine] really helps me...',
            ],
          },
        ] as LessonCard[],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // STAGE 4 — Sức khoẻ & Lối sống (B1)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'stage-4',
    title: 'Stage 4',
    subtitle: 'Sức khoẻ & Lối sống',
    icon: '🌿',
    color: 'from-teal-500 to-emerald-600',
    accentColor: 'teal',
    lessons: [
      {
        id: 'l10',
        stageId: 'stage-4',
        title: 'Từ vựng Sức khoẻ & Lối sống',
        type: 'vocabulary',
        topic: 'Health & Lifestyle',
        level: 'B1',
        description: 'Từ vựng Band 6-7 về sức khoẻ, lối sống và thể chất — xuất hiện thường xuyên trong IELTS',
        xp: 90,
        cards: [
          {
            type: 'vocab',
            word: 'sedentary',
            phonetic: '/ˈsed.ən.tər.i/',
            pos: 'adj.',
            meaning: 'Ít vận động, lười hoạt động thể chất',
            example: 'A sedentary lifestyle is a leading cause of obesity and cardiovascular disease.',
            options: ['Năng động, tích cực', 'Ít vận động, lười vận động', 'Cân bằng, điều độ', 'Khỏe mạnh, tràn năng lượng'],
            answer: 'Ít vận động, lười vận động',
          },
          {
            type: 'vocab',
            word: 'nutrition',
            phonetic: '/njuːˈtrɪʃ.ən/',
            pos: 'n.',
            meaning: 'Dinh dưỡng',
            example: 'Good nutrition is just as important as regular exercise for maintaining a healthy weight.',
            options: ['Thể dục thể thao', 'Dinh dưỡng', 'Thuốc bổ, thực phẩm chức năng', 'Chế độ ăn kiêng'],
            answer: 'Dinh dưỡng',
          },
          {
            type: 'vocab',
            word: 'chronic',
            phonetic: '/ˈkrɒn.ɪk/',
            pos: 'adj.',
            meaning: 'Mãn tính (bệnh kéo dài lâu dài)',
            example: 'Chronic stress can weaken the immune system and lead to serious health problems.',
            options: ['Cấp tính (đột ngột)', 'Mãn tính (kéo dài)', 'Nhẹ, không nghiêm trọng', 'Lây nhiễm, truyền nhiễm'],
            answer: 'Mãn tính (kéo dài)',
          },
          {
            type: 'vocab',
            word: 'well-being',
            phonetic: '/ˈwel.biː.ɪŋ/',
            pos: 'n.',
            meaning: 'Sức khoẻ toàn diện (thể chất & tinh thần)',
            example: 'Schools are increasingly focusing on students\' mental well-being, not just academic results.',
            options: ['Tình trạng thể chất đơn thuần', 'Sức khoẻ toàn diện cả thể chất lẫn tinh thần', 'Thành tích học tập', 'Hoàn cảnh kinh tế'],
            answer: 'Sức khoẻ toàn diện cả thể chất lẫn tinh thần',
          },
          {
            type: 'vocab',
            word: 'preventive',
            phonetic: '/prɪˈven.tɪv/',
            pos: 'adj.',
            meaning: 'Phòng ngừa, ngăn chặn (bệnh tật)',
            example: 'Preventive healthcare, such as regular screenings, is far more cost-effective than treatment.',
            options: ['Điều trị, chữa khỏi bệnh', 'Phòng ngừa, ngăn chặn', 'Khẩn cấp, cấp cứu', 'Phục hồi chức năng'],
            answer: 'Phòng ngừa, ngăn chặn',
          },
          {
            type: 'vocab',
            word: 'immune system',
            phonetic: '/ɪˈmjuːn ˌsɪs.təm/',
            pos: 'n. phrase',
            meaning: 'Hệ miễn dịch',
            example: 'A balanced diet rich in vitamins helps to strengthen your immune system.',
            options: ['Hệ thần kinh', 'Hệ tiêu hoá', 'Hệ miễn dịch', 'Hệ tuần hoàn'],
            answer: 'Hệ miễn dịch',
          },
          {
            type: 'vocab',
            word: 'regime',
            phonetic: '/reɪˈʒiːm/',
            pos: 'n.',
            meaning: 'Chế độ (ăn uống, tập luyện)',
            example: 'Following a strict exercise regime helped her recover quickly after the injury.',
            options: ['Bài tập cụ thể', 'Chế độ (ăn uống, luyện tập)', 'Lịch trình, thời khoá biểu', 'Phương pháp điều trị'],
            answer: 'Chế độ (ăn uống, luyện tập)',
          },
          {
            type: 'vocab',
            word: 'obesity',
            phonetic: '/əˈbiː.sɪ.ti/',
            pos: 'n.',
            meaning: 'Béo phì',
            example: 'Childhood obesity has risen sharply over the past two decades in many countries.',
            options: ['Suy dinh dưỡng', 'Béo phì', 'Tiểu đường', 'Huyết áp cao'],
            answer: 'Béo phì',
          },
        ] as LessonCard[],
      },

      {
        id: 'l11',
        stageId: 'stage-4',
        title: 'Thì Hiện Tại Hoàn Thành',
        type: 'grammar',
        topic: 'Present Perfect',
        level: 'B1',
        description: 'Dùng thì HTHT để nói về kinh nghiệm và thành tích — cốt yếu khi trả lời IELTS Part 1 & 3',
        xp: 90,
        cards: [
          {
            type: 'grammar',
            rule: 'Cấu trúc & 4 công dụng chính',
            explanation: 'Cấu trúc: S + have/has + V3 (past participle). 4 công dụng: (1) Kinh nghiệm trong đời (ever/never), (2) Kết quả đến hiện tại (just/already/yet), (3) Khoảng thời gian kéo dài (for/since), (4) Hành động vừa xảy ra với tác động hiện tại.',
            examples: [
              'I have lived in Ho Chi Minh City for 5 years. (kéo dài đến hiện tại)',
              'She has never tried surfing before. (kinh nghiệm)',
              'I\'ve just finished my IELTS preparation course. (vừa xong)',
              'Have you ever studied abroad? (kinh nghiệm trong đời)',
            ],
            tip: 'for + khoảng thời gian (for 3 years) | since + mốc thời gian (since 2021)',
            question: 'She ___ (study) at this university since September and she loves it.',
            options: ['studied', 'studies', 'has studied', 'was studying'],
            answer: 'has studied',
          },
          {
            type: 'grammar',
            rule: 'Ever / Never / Already / Yet / Just',
            explanation: 'EVER: trải qua chưa? (câu hỏi) | NEVER: chưa bao giờ | ALREADY: đã rồi (khẳng định) | YET: chưa / đã chưa (phủ định/câu hỏi) | JUST: vừa mới xong gần đây.',
            examples: [
              'Have you ever visited Japan? — No, I\'ve never been there.',
              'I\'ve already submitted my application — done last week.',
              'She hasn\'t finished her assignment yet — still working on it.',
              'I\'ve just received some really exciting news about my internship!',
            ],
            tip: 'Yet thường đứng cuối câu. Already thường đứng giữa have và V3.',
            question: 'I\'ve ___ eaten at this restaurant — the food is amazing! (vừa mới ăn xong)',
            options: ['never', 'yet', 'just', 'already'],
            answer: 'just',
          },
          {
            type: 'grammar',
            rule: 'For và Since',
            explanation: 'FOR + khoảng thời gian: for two years, for a long time, for ages, for six months. SINCE + điểm bắt đầu: since 2019, since last year, since I graduated, since childhood.',
            examples: [
              'I\'ve been learning English for over 8 years now.',
              'She\'s worked at this company since she graduated in 2021.',
              'They\'ve lived together since they got married last June.',
              'We haven\'t spoken for ages — maybe two or three years.',
            ],
            tip: 'Test: có thể đặt "How long?" → dùng "for/since" và HTHT. Không thể → dùng QKĐ.',
            question: 'My sister has been interested in medicine ___ she was a child.',
            options: ['for', 'since', 'during', 'from'],
            answer: 'since',
          },
          {
            type: 'grammar',
            rule: 'HTHT vs Quá Khứ Đơn',
            explanation: 'HTHT: không nêu thời gian cụ thể, kết quả còn ảnh hưởng đến hiện tại. QKĐ: có mốc thời gian cụ thể trong quá khứ (yesterday, in 2020, last year). Đây là lỗi phân biệt phổ biến nhất trong IELTS.',
            examples: [
              'I have visited Singapore three times. (kinh nghiệm, không nêu khi nào)',
              'I visited Singapore in 2019. (cụ thể — QKĐ)',
              '✗ I have met her yesterday. (yesterday = QKĐ)',
              '✓ I met her yesterday. / ✓ I have already met her. (không nêu khi nào)',
            ],
            tip: 'Có yesterday/last/in 2020/ago → PHẢI dùng QKĐ. Không có mốc thời gian → HTHT',
            question: 'She ___ (visit) Japan twice, but she\'s never been to Korea.',
            options: ['visited', 'has visited', 'visits', 'was visiting'],
            answer: 'has visited',
          },
          {
            type: 'grammar',
            rule: 'HTHT trong IELTS Speaking & Writing',
            explanation: 'Dùng HTHT trong IELTS để: mô tả kinh nghiệm (I\'ve always been passionate about...), nói về thay đổi (Things have changed dramatically...), làm nền cho câu chuyện (Now that I\'ve explained..., let me tell you...).',
            examples: [
              'I\'ve always been fascinated by technology, which is why I chose... (Band 7)',
              'In recent years, there has been a significant shift in... (Band 7+ Writing)',
              'I\'ve had several opportunities to... which has helped me... (Part 2)',
            ],
            tip: '"I\'ve always + HTHT" là cách mở đầu rất tốt để nói về đam mê và sở thích trong IELTS',
            question: 'Câu nào dùng HTHT đúng và tự nhiên nhất trong IELTS Speaking?',
            options: [
              'I have been to school yesterday.',
              'I\'ve always been interested in environmental issues.',
              'She has visited Paris last summer.',
              'They have gone home two hours ago.',
            ],
            answer: 'I\'ve always been interested in environmental issues.',
          },
        ] as LessonCard[],
      },

      {
        id: 'l12',
        stageId: 'stage-4',
        title: 'IELTS Part 2: Bài nói mở rộng',
        type: 'speaking',
        topic: 'Extended Speaking',
        level: 'B1',
        description: 'Học cách trả lời cue card IELTS Part 2 — bài nói 1-2 phút có cấu trúc, mạch lạc và đầy đủ nội dung',
        xp: 130,
        cards: [
          {
            type: 'speaking',
            prompt: 'Describe a healthy habit you have developed.\nYou should say:\n• what the habit is\n• when and how you started it\n• how it has changed your life\nAnd explain why you think it is beneficial.',
            hint: 'Đây là cue card IELTS Part 2. Có 1 phút chuẩn bị, nói 1-2 phút. Cấu trúc: Mở → Chi tiết 3 bullet points → Kết/đánh giá.',
            samplePhrases: [
              'The healthy habit I\'d like to talk about is [habit], which I started about [time] ago.',
              'I first developed this habit when I realised that I was feeling [problem], so I decided to...',
              'Since I started [habit], I\'ve noticed a significant improvement in my [energy/mood/health].',
              'I believe this habit is beneficial because it not only [benefit 1] but also [benefit 2].',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Describe a time when you achieved something you were proud of.\nYou should say:\n• what the achievement was\n• how long it took to achieve it\n• what challenges you faced\nAnd explain why you felt so proud.',
            hint: 'Kể chuyện theo trình tự: Bối cảnh → Thách thức → Hành động → Kết quả → Cảm xúc. Dùng thì quá khứ. Thêm cảm xúc thật để câu chuyện sống động.',
            samplePhrases: [
              'I\'d like to talk about the time when I [achievement] — it was back in [time].',
              'At first, I found it really challenging because... but I kept pushing myself by...',
              'After [period] of hard work and dedication, I finally managed to...',
              'The moment I [achieved the goal], I felt an overwhelming sense of pride because...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Describe an interesting person you know.\nYou should say:\n• who this person is\n• how you know them\n• what makes them interesting\nAnd explain what you have learned from them.',
            hint: 'Chọn người thực sự ấn tượng với bạn. Mô tả tính cách, điều thú vị họ làm, và ảnh hưởng của họ với bạn. Tránh mô tả quá chung chung.',
            samplePhrases: [
              'The person I\'d like to describe is [name/relation], who I\'ve known for [time].',
              'What makes [him/her] so interesting is that [specific quality or story].',
              'One thing that really stands out about [them] is their ability to...',
              'I\'ve learned so much from [him/her], particularly the importance of...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Describe a place you visited that had a strong impact on you.\nYou should say:\n• where the place is and how you got there\n• what you did there\n• how you felt when you were there\nAnd explain why it had such an impact on you.',
            hint: 'Mô tả chi tiết giúp bài nói sống động: màu sắc, mùi, cảm giác, âm thanh. Nói tại sao nơi đó ý nghĩa với bạn — không chỉ liệt kê những gì đã thấy.',
            samplePhrases: [
              'I\'d like to describe [place], which I visited [when]. It was truly [adjective].',
              'When I first arrived, I was immediately struck by [striking feature].',
              'The atmosphere there was [adjective] — there was a sense of [feeling] everywhere.',
              'This place left such a lasting impression on me because it made me realise that...',
            ],
          },
        ] as LessonCard[],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // STAGE 5 — Công nghệ & Môi trường (B1)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'stage-5',
    title: 'Stage 5',
    subtitle: 'Công nghệ & Môi trường',
    icon: '🌍',
    color: 'from-blue-500 to-indigo-600',
    accentColor: 'blue',
    lessons: [
      {
        id: 'l13',
        stageId: 'stage-5',
        title: 'Từ vựng Công nghệ & AI',
        type: 'vocabulary',
        topic: 'Technology & AI',
        level: 'B1',
        description: 'Từ vựng Band 6-7 về công nghệ số và AI — chủ đề hot nhất trong đề thi IELTS hiện đại',
        xp: 100,
        cards: [
          {
            type: 'vocab',
            word: 'artificial intelligence',
            phonetic: '/ˌɑː.tɪ.fɪʃ.əl ɪnˈtel.ɪ.dʒəns/',
            pos: 'n.',
            meaning: 'Trí tuệ nhân tạo (AI)',
            example: 'Artificial intelligence is transforming industries from healthcare to transportation.',
            options: ['Trí tuệ con người', 'Trí tuệ nhân tạo (AI)', 'Công nghệ thông tin', 'Dữ liệu số'],
            answer: 'Trí tuệ nhân tạo (AI)',
          },
          {
            type: 'vocab',
            word: 'innovation',
            phonetic: '/ˌɪn.əˈveɪ.ʃən/',
            pos: 'n.',
            meaning: 'Đổi mới sáng tạo',
            example: 'Technological innovation has accelerated at an unprecedented pace in recent decades.',
            options: ['Cải tiến nhỏ', 'Đổi mới sáng tạo', 'Quy trình truyền thống', 'Sản phẩm cũ'],
            answer: 'Đổi mới sáng tạo',
          },
          {
            type: 'vocab',
            word: 'digital divide',
            phonetic: '/ˈdɪdʒ.ɪ.təl dɪˈvaɪd/',
            pos: 'n. phrase',
            meaning: 'Khoảng cách kỹ thuật số (bất bình đẳng tiếp cận công nghệ)',
            example: 'The digital divide between rural and urban areas remains a significant challenge.',
            options: ['Tốc độ internet nhanh', 'Khoảng cách kỹ thuật số', 'Nền tảng chia sẻ', 'Màn hình kỹ thuật số'],
            answer: 'Khoảng cách kỹ thuật số',
          },
          {
            type: 'vocab',
            word: 'automation',
            phonetic: '/ˌɔː.təˈmeɪ.ʃən/',
            pos: 'n.',
            meaning: 'Tự động hoá',
            example: 'Automation has replaced many repetitive jobs, raising concerns about unemployment.',
            options: ['Tự động hoá', 'Phát triển thủ công', 'Đào tạo nghề', 'Năng suất lao động'],
            answer: 'Tự động hoá',
          },
          {
            type: 'vocab',
            word: 'algorithm',
            phonetic: '/ˈæl.ɡə.rɪ.ðəm/',
            pos: 'n.',
            meaning: 'Thuật toán',
            example: 'Social media algorithms determine what content users see, influencing their views.',
            options: ['Phần mềm ứng dụng', 'Dữ liệu người dùng', 'Thuật toán', 'Mạng xã hội'],
            answer: 'Thuật toán',
          },
          {
            type: 'vocab',
            word: 'cybersecurity',
            phonetic: '/ˌsaɪ.bəsɪˈkjʊə.rɪ.ti/',
            pos: 'n.',
            meaning: 'An ninh mạng',
            example: 'Companies are investing heavily in cybersecurity to protect sensitive customer data.',
            options: ['Hệ thống mạng', 'An ninh mạng', 'Cơ sở hạ tầng số', 'Quyền riêng tư'],
            answer: 'An ninh mạng',
          },
          {
            type: 'vocab',
            word: 'screen time',
            phonetic: '/ˈskriːn taɪm/',
            pos: 'n.',
            meaning: 'Thời gian dùng màn hình thiết bị điện tử',
            example: 'Excessive screen time in children has been linked to shorter attention spans.',
            options: ['Thời gian giải trí', 'Thời gian dùng màn hình', 'Chương trình truyền hình', 'Thời gian đọc sách'],
            answer: 'Thời gian dùng màn hình',
          },
          {
            type: 'vocab',
            word: 'disruptive',
            phonetic: '/dɪsˈrʌp.tɪv/',
            pos: 'adj.',
            meaning: 'Mang tính phá vỡ (thay đổi cách thức cũ hoàn toàn)',
            example: 'Smartphones were a truly disruptive technology that changed how we communicate.',
            options: ['Dần dần, từng bước', 'Mang tính phá vỡ toàn diện', 'Gây phiền phức, làm gián đoạn', 'Ổn định, bền vững'],
            answer: 'Mang tính phá vỡ toàn diện',
          },
        ] as LessonCard[],
      },

      {
        id: 'l14',
        stageId: 'stage-5',
        title: 'Từ vựng Môi trường & Bền vững',
        type: 'vocabulary',
        topic: 'Environment',
        level: 'B1',
        description: 'Từ vựng Band 6-7 về môi trường và phát triển bền vững — chủ đề quan trọng nhất trong IELTS hiện nay',
        xp: 100,
        cards: [
          {
            type: 'vocab',
            word: 'sustainable',
            phonetic: '/səˈsteɪ.nə.bəl/',
            pos: 'adj.',
            meaning: 'Bền vững (không gây hại môi trường lâu dài)',
            example: 'Sustainable energy sources like solar and wind power are crucial for our future.',
            options: ['Rẻ, tiết kiệm chi phí', 'Bền vững, không gây hại lâu dài', 'Tái chế được', 'Hiện đại, tiên tiến'],
            answer: 'Bền vững, không gây hại lâu dài',
          },
          {
            type: 'vocab',
            word: 'carbon footprint',
            phonetic: '/ˈkɑː.bən ˈfʊt.prɪnt/',
            pos: 'n.',
            meaning: 'Dấu chân carbon (lượng khí CO2 thải ra)',
            example: 'Flying is one of the biggest contributors to an individual\'s carbon footprint.',
            options: ['Dấu chân carbon (lượng CO2 thải ra)', 'Ô nhiễm không khí', 'Biến đổi khí hậu', 'Năng lượng tái tạo'],
            answer: 'Dấu chân carbon (lượng CO2 thải ra)',
          },
          {
            type: 'vocab',
            word: 'biodiversity',
            phonetic: '/ˌbaɪ.əʊ.daɪˈvɜː.sɪ.ti/',
            pos: 'n.',
            meaning: 'Đa dạng sinh học',
            example: 'Deforestation poses a severe threat to biodiversity in tropical rainforests.',
            options: ['Hệ sinh thái ổn định', 'Đa dạng sinh học', 'Tái tạo rừng', 'Bảo vệ động vật'],
            answer: 'Đa dạng sinh học',
          },
          {
            type: 'vocab',
            word: 'greenhouse gas',
            phonetic: '/ˈɡriːn.haʊs ɡæs/',
            pos: 'n.',
            meaning: 'Khí nhà kính',
            example: 'Reducing greenhouse gas emissions is the most urgent environmental challenge today.',
            options: ['Khí độc hại', 'Khí nhà kính', 'Khí ozone', 'Không khí sạch'],
            answer: 'Khí nhà kính',
          },
          {
            type: 'vocab',
            word: 'renewable energy',
            phonetic: '/rɪˌnjuː.ə.bəl ˈen.ə.dʒi/',
            pos: 'n. phrase',
            meaning: 'Năng lượng tái tạo',
            example: 'Vietnam has made significant investments in renewable energy, especially wind and solar.',
            options: ['Năng lượng hạt nhân', 'Nhiên liệu hoá thạch', 'Năng lượng tái tạo', 'Điện lưới quốc gia'],
            answer: 'Năng lượng tái tạo',
          },
          {
            type: 'vocab',
            word: 'conservation',
            phonetic: '/ˌkɒn.səˈveɪ.ʃən/',
            pos: 'n.',
            meaning: 'Bảo tồn (thiên nhiên, tài nguyên)',
            example: 'Wildlife conservation efforts have helped several endangered species recover.',
            options: ['Khai thác tài nguyên', 'Bảo tồn thiên nhiên', 'Nghiên cứu khoa học', 'Trồng cây gây rừng'],
            answer: 'Bảo tồn thiên nhiên',
          },
          {
            type: 'vocab',
            word: 'deforestation',
            phonetic: '/ˌdiː.fɒr.ɪˈsteɪ.ʃən/',
            pos: 'n.',
            meaning: 'Nạn phá rừng',
            example: 'Deforestation for agriculture destroys habitats and contributes to global warming.',
            options: ['Trồng thêm rừng', 'Nạn phá rừng', 'Cháy rừng tự nhiên', 'Rừng nguyên sinh'],
            answer: 'Nạn phá rừng',
          },
          {
            type: 'vocab',
            word: 'eco-friendly',
            phonetic: '/ˈiː.kəʊ ˌfrend.li/',
            pos: 'adj.',
            meaning: 'Thân thiện với môi trường',
            example: 'Choosing eco-friendly products is one of the easiest ways to reduce your impact.',
            options: ['Đắt tiền, xa xỉ', 'Thân thiện với môi trường', 'Được sản xuất tại địa phương', 'Chất lượng cao'],
            answer: 'Thân thiện với môi trường',
          },
        ] as LessonCard[],
      },

      {
        id: 'l15',
        stageId: 'stage-5',
        title: 'IELTS Part 3: Thảo luận xã hội',
        type: 'speaking',
        topic: 'Social Discussion',
        level: 'B1',
        description: 'Luyện tập trả lời IELTS Part 3 — câu hỏi thảo luận mang tính xã hội, cần ý kiến và lập luận rõ ràng',
        xp: 140,
        cards: [
          {
            type: 'speaking',
            prompt: 'Do you think governments should do more to protect the environment? What measures could they take?',
            hint: 'Câu hỏi IELTS Part 3 — cần lập trường rõ ràng + 2-3 biện pháp cụ thể + ví dụ. Dùng: "I strongly believe...", "One effective measure would be..."',
            samplePhrases: [
              'I firmly believe that governments have a responsibility to lead on environmental protection.',
              'One effective measure would be to introduce stricter regulations on carbon emissions.',
              'In addition, governments could invest heavily in renewable energy infrastructure, which...',
              'Of course, individual action also plays a role, but without government policy...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'How has technology changed the way people communicate with each other? Is this change mostly positive or negative?',
            hint: 'Nêu thay đổi cụ thể (cách giao tiếp, tốc độ, phạm vi), sau đó đánh giá cân bằng (both sides) trước khi đưa ra lập trường cuối.',
            samplePhrases: [
              'Technology has fundamentally transformed communication in terms of speed, reach and convenience.',
              'On the positive side, we can now instantly connect with people across the globe...',
              'However, there are concerns that digital communication lacks the depth and nuance of...',
              'On balance, I think the benefits outweigh the drawbacks, provided that...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Some people think that technology is making people less creative. Do you agree or disagree?',
            hint: 'Đây là câu hỏi agree/disagree — nên nêu rõ lập trường ngay từ đầu, sau đó đưa ra 2 lý do có ví dụ. Tránh ngồi giữa quá nhiều.',
            samplePhrases: [
              'I would actually disagree with this view, and here\'s why...',
              'While it\'s true that technology can be a distraction, it also provides...',
              'Take graphic design as an example — digital tools have expanded what designers can...',
              'The key issue isn\'t technology itself, but rather how we choose to use it.',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Do you think it is the responsibility of individuals or companies to protect the environment?',
            hint: 'Câu hỏi lưỡng lựa (individual vs company). Thay vì chọn một bên, bạn có thể lập luận rằng cả hai cần có trách nhiệm. Điều quan trọng là lập luận phải nhất quán.',
            samplePhrases: [
              'I think it\'s a shared responsibility — companies and individuals both have a role to play.',
              'Companies arguably have a greater obligation because they operate at a much larger scale.',
              'That said, consumers also hold significant power through their purchasing decisions.',
              'Ultimately, the most effective approach is a combination of corporate accountability and...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'What impact do you think artificial intelligence will have on society in the next 20 years?',
            hint: 'Câu hỏi tương lai — dùng will/might/could. Nêu tác động tích cực (y tế, năng suất) và rủi ro (việc làm, quyền riêng tư). Kết bằng dự đoán cân bằng.',
            samplePhrases: [
              'I think AI will have a profound and far-reaching impact on virtually every sector.',
              'In healthcare, AI could revolutionize diagnosis and treatment, potentially saving millions of lives.',
              'On the other hand, there are legitimate concerns about job displacement, particularly for...',
              'The key will be ensuring that the benefits of AI are distributed equitably across society.',
            ],
          },
        ] as LessonCard[],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // STAGE 6 — B2 Nâng cao (B2)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'stage-6',
    title: 'Stage 6',
    subtitle: 'B2 Nâng cao',
    icon: '🏆',
    color: 'from-rose-500 to-orange-500',
    accentColor: 'rose',
    lessons: [
      {
        id: 'l16',
        stageId: 'stage-6',
        title: 'Từ vựng Xã hội & Văn hoá',
        type: 'vocabulary',
        topic: 'Society & Culture',
        level: 'B2',
        description: 'Từ vựng Band 7-8 về xã hội, văn hoá và các vấn đề đương đại — để đạt điểm cao nhất IELTS',
        xp: 150,
        cards: [
          {
            type: 'vocab',
            word: 'urbanization',
            phonetic: '/ˌɜː.bə.naɪˈzeɪ.ʃən/',
            pos: 'n.',
            meaning: 'Đô thị hoá',
            example: 'Rapid urbanization has led to overcrowding and infrastructure strain in major cities.',
            options: ['Công nghiệp hoá', 'Đô thị hoá', 'Hiện đại hoá', 'Phát triển nông thôn'],
            answer: 'Đô thị hoá',
          },
          {
            type: 'vocab',
            word: 'inequality',
            phonetic: '/ˌɪn.ɪˈkwɒl.ɪ.ti/',
            pos: 'n.',
            meaning: 'Bất bình đẳng',
            example: 'Income inequality between urban and rural populations continues to widen.',
            options: ['Sự công bằng', 'Bất bình đẳng', 'Nghèo đói', 'Phân biệt đối xử'],
            answer: 'Bất bình đẳng',
          },
          {
            type: 'vocab',
            word: 'multicultural',
            phonetic: '/ˌmʌl.tiˈkʌl.tʃər.əl/',
            pos: 'adj.',
            meaning: 'Đa văn hoá',
            example: 'Singapore is a truly multicultural society where diverse traditions coexist harmoniously.',
            options: ['Đa ngôn ngữ', 'Đa văn hoá', 'Quốc tế hoá', 'Hội nhập xã hội'],
            answer: 'Đa văn hoá',
          },
          {
            type: 'vocab',
            word: 'stereotype',
            phonetic: '/ˈster.i.ə.taɪp/',
            pos: 'n.',
            meaning: 'Định kiến, khuôn mẫu cứng nhắc',
            example: 'It\'s important to challenge stereotypes rather than accepting them as truth.',
            options: ['Định kiến, khuôn mẫu', 'Quan điểm cá nhân', 'Truyền thống văn hoá', 'Giá trị đạo đức'],
            answer: 'Định kiến, khuôn mẫu',
          },
          {
            type: 'vocab',
            word: 'empathy',
            phonetic: '/ˈem.pə.θi/',
            pos: 'n.',
            meaning: 'Sự đồng cảm, thấu hiểu',
            example: 'Developing empathy for people from different backgrounds is essential in a globalised world.',
            options: ['Sự thương hại', 'Sự đồng cảm, thấu hiểu', 'Sự tôn trọng', 'Sự chấp nhận'],
            answer: 'Sự đồng cảm, thấu hiểu',
          },
          {
            type: 'vocab',
            word: 'social cohesion',
            phonetic: '/ˈsəʊ.ʃəl kəʊˈhiː.ʒən/',
            pos: 'n. phrase',
            meaning: 'Gắn kết xã hội',
            example: 'Shared public spaces and community events play a vital role in promoting social cohesion.',
            options: ['Trật tự xã hội', 'Gắn kết xã hội', 'Đoàn kết dân tộc', 'Ổn định chính trị'],
            answer: 'Gắn kết xã hội',
          },
          {
            type: 'vocab',
            word: 'globalization',
            phonetic: '/ˌɡləʊ.bəl.aɪˈzeɪ.ʃən/',
            pos: 'n.',
            meaning: 'Toàn cầu hoá',
            example: 'Globalization has created economic opportunities but also led to cultural homogenization.',
            options: ['Toàn cầu hoá', 'Phát triển kinh tế', 'Hội nhập khu vực', 'Trao đổi văn hoá'],
            answer: 'Toàn cầu hoá',
          },
          {
            type: 'vocab',
            word: 'disparity',
            phonetic: '/dɪˈspær.ɪ.ti/',
            pos: 'n.',
            meaning: 'Sự chênh lệch, khác biệt lớn',
            example: 'There is a stark disparity in educational opportunities between wealthy and poor regions.',
            options: ['Sự tương đồng', 'Sự chênh lệch, khác biệt lớn', 'Sự bất công', 'Khoảng cách địa lý'],
            answer: 'Sự chênh lệch, khác biệt lớn',
          },
        ] as LessonCard[],
      },

      {
        id: 'l17',
        stageId: 'stage-6',
        title: 'Câu điều kiện & Bị động nâng cao',
        type: 'grammar',
        topic: 'Advanced Conditionals & Passive',
        level: 'B2',
        description: 'Cấu trúc ngữ pháp Band 7-8: điều kiện hỗn hợp, bị động nâng cao — để đạt điểm cao Grammatical Range',
        xp: 150,
        cards: [
          {
            type: 'grammar',
            rule: 'Điều kiện loại 2 (Unreal Present/Future)',
            explanation: 'Điều kiện loại 2: If + S + V-ed/were, S + would/could/might + V. Diễn tả tình huống KHÔNG thực ở hiện tại hoặc tương lai — điều không xảy ra hoặc khó xảy ra.',
            examples: [
              'If I had more free time, I would learn a third language.',
              'If she were the president, she would invest more in education.',
              'If we didn\'t have smartphones, life would be very different.',
            ],
            tip: 'Với "be" ở điều kiện loại 2, dùng "were" cho mọi ngôi: "If I were you..." (không phải "was")',
            question: 'If the government ___ (invest) more in public transport, fewer people would drive.',
            options: ['invests', 'invested', 'will invest', 'had invested'],
            answer: 'invested',
          },
          {
            type: 'grammar',
            rule: 'Điều kiện loại 3 (Unreal Past)',
            explanation: 'Điều kiện loại 3: If + S + had + V3, S + would/could/might + have + V3. Diễn tả tình huống KHÔNG THỰC trong quá khứ — điều đã không xảy ra nhưng giả định nó xảy ra.',
            examples: [
              'If I had studied harder, I would have passed the exam.',
              'If she had taken that job offer, she would have moved abroad.',
              'The situation could have been much worse if they hadn\'t acted quickly.',
            ],
            tip: 'Loại 3 = nhìn lại quá khứ và hối tiếc / tưởng tượng kết quả khác. Rất hay trong IELTS Part 2 khi kể chuyện.',
            question: 'If I ___ (not take) that scholarship opportunity, my life would have been very different.',
            options: ["didn't take", "hadn't taken", "wouldn't take", "won't take"],
            answer: "hadn't taken",
          },
          {
            type: 'grammar',
            rule: 'Điều kiện hỗn hợp (Mixed Conditionals)',
            explanation: 'Điều kiện hỗn hợp kết hợp loại 2 và 3: (a) Quá khứ → Hiện tại: If + had done, would be (b) Hiện tại → Quá khứ: If + were, would have done. Dùng khi nguyên nhân và kết quả ở 2 thời gian khác nhau.',
            examples: [
              'If I had studied medicine, I would be a doctor now. (QK→HT)',
              'If she weren\'t so shy, she would have applied for that job. (HT→QK)',
              'If he had taken better care of his health, he wouldn\'t be ill now.',
            ],
            tip: 'Mixed conditional = Band 8 grammar trong IELTS. Dùng đúng → examiner ấn tượng ngay.',
            question: 'If she ___ (work) harder at school, she would have a better job now. (QK→HT)',
            options: ['works', 'worked', 'had worked', 'would work'],
            answer: 'had worked',
          },
          {
            type: 'grammar',
            rule: 'Bị động nâng cao với Modal Verbs',
            explanation: 'Câu bị động với modal verbs: S + modal + be + V3. Hoàn thành: S + modal + have been + V3. Dùng nhiều trong văn viết và thảo luận học thuật.',
            examples: [
              'This policy should be reviewed immediately. (hiện tại)',
              'The problem could have been prevented with better planning. (quá khứ)',
              'More resources need to be allocated to education. (cần thiết)',
              'Emissions must be reduced significantly by 2030. (bắt buộc)',
            ],
            tip: 'Modal + be + V3 = rất phổ biến trong IELTS Writing Task 2 khi đưa ra đề xuất, kiến nghị',
            question: 'The new regulations ___ (enforce) strictly if they are to be effective.',
            options: ['must enforce', 'must be enforced', 'must have enforced', 'are enforced'],
            answer: 'must be enforced',
          },
          {
            type: 'grammar',
            rule: 'It is believed/said/reported (Impersonal passive)',
            explanation: 'Bị động vô nhân xưng dùng trong văn học thuật và báo cáo: It + is/was + V3 + that clause. Cấu trúc thay thế: S + is said/believed/reported/thought + to V.',
            examples: [
              'It is widely believed that climate change poses the greatest threat to humanity.',
              'It was reported that the policy had failed to achieve its intended goals.',
              'The new technology is thought to revolutionize the healthcare sector.',
              'Urbanization is said to be one of the defining trends of the 21st century.',
            ],
            tip: 'Cách viết học thuật: dùng "It is said/believed/argued that..." thay vì "People say/believe..."',
            question: 'It ___ (widely believe) that regular exercise can prevent many chronic diseases.',
            options: ['widely believes', 'is widely believed', 'widely believed', 'has widely believed'],
            answer: 'is widely believed',
          },
          {
            type: 'grammar',
            rule: 'Inversion (Đảo ngữ) — Band 8+',
            explanation: 'Đảo ngữ với: Not only...but also, Never, Rarely, Seldom, Hardly...when, Only + adverbial phrase. Đảo ngữ làm câu nhấn mạnh và sáng tạo hơn — đặc trưng Band 8.',
            examples: [
              'Not only does exercise improve physical health, but it also enhances mental wellbeing.',
              'Rarely have we seen such rapid technological advancement in history.',
              'Never before has the need for environmental action been so urgent.',
              'Only by working together can we address global challenges like climate change.',
            ],
            tip: 'Quy tắc: Sau Not only / Never / Rarely → đảo trợ động từ lên trước chủ ngữ: Not only DOES she...',
            question: 'Not only ___ the new policy reduce costs, but it also improved efficiency.',
            options: ['the new policy reduced', 'did the new policy reduce', 'the new policy did reduce', 'reduced the new policy'],
            answer: 'did the new policy reduce',
          },
        ] as LessonCard[],
      },

      {
        id: 'l18',
        stageId: 'stage-6',
        title: 'IELTS Collocations & Discourse Markers',
        type: 'vocabulary',
        topic: 'Advanced Vocabulary',
        level: 'B2',
        description: 'Collocations và discourse markers Band 7-8 để liên kết ý tưởng mạch lạc và tự nhiên trong IELTS',
        xp: 150,
        cards: [
          {
            type: 'vocab',
            word: 'raise awareness',
            phonetic: '/reɪz əˈweər.nəs/',
            pos: 'collocation',
            meaning: 'Nâng cao nhận thức',
            example: 'Social media campaigns have been effective in raising awareness about mental health.',
            options: ['Thu thập thông tin', 'Nâng cao nhận thức', 'Tuyên truyền sai lệch', 'Mở rộng kiến thức'],
            answer: 'Nâng cao nhận thức',
          },
          {
            type: 'vocab',
            word: 'tackle an issue',
            phonetic: '/ˈtæk.əl ən ˈɪʃ.uː/',
            pos: 'collocation',
            meaning: 'Giải quyết, xử lý vấn đề',
            example: 'Governments need to tackle the issue of plastic pollution more aggressively.',
            options: ['Bỏ qua vấn đề', 'Giải quyết, xử lý vấn đề', 'Điều tra vấn đề', 'Công nhận vấn đề'],
            answer: 'Giải quyết, xử lý vấn đề',
          },
          {
            type: 'vocab',
            word: 'pose a threat',
            phonetic: '/pəʊz ə θret/',
            pos: 'collocation',
            meaning: 'Đặt ra mối đe doạ',
            example: 'Climate change poses a serious threat to food security around the world.',
            options: ['Loại bỏ mối đe doạ', 'Đặt ra mối đe doạ', 'Đánh giá rủi ro', 'Đương đầu thử thách'],
            answer: 'Đặt ra mối đe doạ',
          },
          {
            type: 'vocab',
            word: 'on the other hand',
            phonetic: '/ɒn ðə ˈʌð.ər hænd/',
            pos: 'discourse marker',
            meaning: 'Mặt khác (đối lập ý kiến)',
            example: 'Technology has made life more convenient. On the other hand, it has also increased stress.',
            options: ['Vì vậy, do đó', 'Mặt khác (đối lập)', 'Hơn nữa, ngoài ra', 'Kết luận lại'],
            answer: 'Mặt khác (đối lập)',
          },
          {
            type: 'vocab',
            word: 'in contrast',
            phonetic: '/ɪn ˈkɒn.trɑːst/',
            pos: 'discourse marker',
            meaning: 'Trái lại, tương phản với',
            example: 'Urban areas have seen rapid growth. In contrast, many rural regions are declining.',
            options: ['Tương tự, giống như vậy', 'Trái lại, tương phản', 'Hệ quả là, vì vậy', 'Tiếp theo, sau đó'],
            answer: 'Trái lại, tương phản',
          },
          {
            type: 'vocab',
            word: 'it is worth noting that',
            phonetic: '/ɪt ɪz wɜːθ ˈnəʊ.tɪŋ ðæt/',
            pos: 'discourse marker',
            meaning: 'Đáng lưu ý rằng...',
            example: 'It is worth noting that not all studies support this conclusion.',
            options: ['Tuy nhiên, mặc dù', 'Đáng lưu ý rằng', 'Nói tóm lại', 'Ví dụ như, chẳng hạn'],
            answer: 'Đáng lưu ý rằng',
          },
          {
            type: 'vocab',
            word: 'make a significant contribution',
            phonetic: '/meɪk ə sɪɡˈnɪf.ɪ.kənt ˌkɒn.trɪˈbjuː.ʃən/',
            pos: 'collocation',
            meaning: 'Đóng góp đáng kể',
            example: 'Renewable energy has already made a significant contribution to reducing emissions.',
            options: ['Tạo ra sự khác biệt nhỏ', 'Đóng góp đáng kể', 'Giải quyết hoàn toàn', 'Cản trở sự tiến bộ'],
            answer: 'Đóng góp đáng kể',
          },
          {
            type: 'vocab',
            word: 'have a profound impact on',
            phonetic: '/hæv ə prəˈfaʊnd ˈɪm.pækt ɒn/',
            pos: 'collocation',
            meaning: 'Có tác động sâu sắc đến',
            example: 'Social media has had a profound impact on how young people form their identities.',
            options: ['Tác động nhẹ đến', 'Có tác động sâu sắc đến', 'Hoàn toàn thay đổi', 'Liên quan đến'],
            answer: 'Có tác động sâu sắc đến',
          },
        ] as LessonCard[],
      },

      {
        id: 'l19',
        stageId: 'stage-6',
        title: 'Câu phức & Mệnh đề quan hệ',
        type: 'grammar',
        topic: 'Complex Sentences',
        level: 'B2',
        description: 'Xây dựng câu phức và mệnh đề quan hệ đa dạng — điều kiện để đạt Band 7+ về Grammatical Range',
        xp: 150,
        cards: [
          {
            type: 'grammar',
            rule: 'Mệnh đề quan hệ xác định (Defining Relative Clauses)',
            explanation: 'Mệnh đề quan hệ xác định: giới hạn, xác định danh từ — KHÔNG dùng dấu phẩy. Dùng: who (người), which/that (vật), where (nơi), when (thời gian), whose (sở hữu).',
            examples: [
              'The researcher who published this study won the Nobel Prize.',
              'The policy that was introduced last year has had limited success.',
              'This is the city where I grew up and studied for my degree.',
              'Students whose grades fall below average must attend extra sessions.',
            ],
            tip: 'Xác định = bỏ đi thì câu mất nghĩa. Không xác định = bỏ đi câu vẫn đủ nghĩa (có dấu phẩy)',
            question: 'The scientist ___ discovered this treatment received international recognition.',
            options: ['which', 'whose', 'who', 'whom'],
            answer: 'who',
          },
          {
            type: 'grammar',
            rule: 'Mệnh đề quan hệ không xác định (Non-defining)',
            explanation: 'Mệnh đề quan hệ không xác định: thêm thông tin bổ sung, LUÔN dùng dấu phẩy. KHÔNG dùng "that". Quan trọng trong văn viết học thuật để làm câu phong phú hơn.',
            examples: [
              'Professor Smith, who has taught here for 30 years, is retiring next month.',
              'The Amazon rainforest, which covers 60% of Brazil, faces serious deforestation threats.',
              'My hometown, where I spent my entire childhood, has changed dramatically.',
            ],
            tip: 'Non-defining: dùng WHO cho người, WHICH cho vật — KHÔNG dùng THAT trong non-defining',
            question: 'Ho Chi Minh City, ___ is the largest city in Vietnam, has a population of 9 million.',
            options: ['that', 'who', 'which', 'where'],
            answer: 'which',
          },
          {
            type: 'grammar',
            rule: 'Câu phức với các liên từ phụ (Subordinating conjunctions)',
            explanation: 'Liên từ phụ tạo câu phức: thời gian (when, while, before, after, once), nguyên nhân (because, since, as), nhượng bộ (although, even though, despite the fact that), điều kiện (if, unless, provided that), kết quả (so that, in order that).',
            examples: [
              'Although the policy has been controversial, it has achieved significant results.',
              'Since renewable energy has become more affordable, adoption has increased rapidly.',
              'Unless governments take immediate action, the situation will continue to worsen.',
              'Once people understand the risks, they are more likely to change their behaviour.',
            ],
            tip: '"Although/Even though/Despite" KHÔNG cần "but" đi kèm. Đây là lỗi phổ biến!',
            question: '___ the treatment was expensive, it proved highly effective in most patients.',
            options: ['Despite', 'Although', 'However', 'In spite'],
            answer: 'Although',
          },
          {
            type: 'grammar',
            rule: 'Rút gọn mệnh đề (Reduced Clauses) — Band 7+',
            explanation: 'Rút gọn mệnh đề quan hệ bằng cách bỏ relative pronoun + be: "who is" → V-ing (active) hoặc V3 (passive). Làm câu gọn, học thuật hơn.',
            examples: [
              'Students studying abroad often develop strong cross-cultural skills. (who are studying)',
              'The results obtained from this study suggest a strong correlation. (which were obtained)',
              'Issues raised by the committee will be addressed in the next meeting. (which were raised)',
              'People living in poverty deserve greater government support. (who are living)',
            ],
            tip: 'Rút gọn active → V-ing. Rút gọn passive → V3 (past participle). Không cần who/which.',
            question: 'The data ___ (collect) over ten years shows a clear upward trend. (rút gọn passive)',
            options: ['collecting', 'collected', 'which collected', 'who collected'],
            answer: 'collected',
          },
          {
            type: 'grammar',
            rule: 'Cleft sentences (Câu chẻ — nhấn mạnh)',
            explanation: 'Câu chẻ dùng để nhấn mạnh một thành phần trong câu. Cấu trúc: It is/was + [thông tin nhấn mạnh] + that/who + [phần còn lại]. Dùng nhiều trong IELTS Speaking để tạo sắc thái nhấn mạnh.',
            examples: [
              'It is education that has the greatest impact on a country\'s development.',
              'It was the increase in screen time that caused the decline in reading habits.',
              'It is governments, not individuals, that must take the lead on climate policy.',
            ],
            tip: '"It is... that/who..." = cách nhấn mạnh tự nhiên và học thuật. Dùng trong IELTS Part 3!',
            question: 'It is ___ young people that are most affected by the rise in housing costs.',
            options: ['them', 'those', 'these', 'this'],
            answer: 'those',
          },
        ] as LessonCard[],
      },

      {
        id: 'l20',
        stageId: 'stage-6',
        title: 'IELTS Part 3: Tranh luận nâng cao',
        type: 'speaking',
        topic: 'Advanced Discussion',
        level: 'B2',
        description: 'Masterclass IELTS Part 3 — lập luận sắc sảo, ngôn ngữ học thuật và trả lời câu hỏi trừu tượng tầm Band 7+',
        xp: 200,
        cards: [
          {
            type: 'speaking',
            prompt: 'Some people argue that social media has done more harm than good. To what extent do you agree with this view?',
            hint: 'Câu hỏi phức tạp — nêu lập trường ngay, sau đó thừa nhận phản luận, rồi củng cố lập trường bằng lý do mạnh hơn. Dùng academic hedging: "I would argue that...", "While it is true that..., the fact remains that..."',
            samplePhrases: [
              'I would argue that while social media has its drawbacks, it would be an overstatement to say it has done more harm than good.',
              'It is undeniable that platforms like Facebook and Instagram have been linked to anxiety and misinformation.',
              'However, the positive potential — connecting communities, amplifying marginalised voices, enabling activism — should not be underestimated.',
              'Ultimately, the impact depends heavily on how platforms are regulated and how users are educated to use them responsibly.',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Do you think that economic development should take priority over environmental protection? What is your view?',
            hint: 'Đây là false dilemma — đừng chọn một bên hoàn toàn. Lập luận rằng hai điều này có thể đồng hành (sustainable development). Dùng: "The premise of this question assumes... however..."',
            samplePhrases: [
              'I think the framing of this as an either/or choice is somewhat misleading.',
              'The concept of sustainable development demonstrates that economic growth and environmental protection are not mutually exclusive.',
              'Countries like Denmark have shown that it\'s entirely possible to have a thriving economy built on green industries.',
              'That said, for developing nations facing pressing poverty, the calculus may be more complex, and...',
            ],
          },
          {
            type: 'speaking',
            prompt: 'How do you think education systems should change to prepare students for the future job market?',
            hint: 'Câu hỏi về giáo dục — nêu vấn đề hiện tại, sau đó đề xuất 2-3 thay đổi cụ thể. Dùng: "There is a strong case for...", "One fundamental shift that needs to happen is..."',
            samplePhrases: [
              'I think one of the most fundamental changes needed is a shift away from rote learning towards critical thinking and problem-solving.',
              'There is a compelling case for incorporating digital literacy and AI skills into curricula from an early age.',
              'Equally important is developing soft skills — collaboration, adaptability and communication — which are increasingly valued by employers.',
              'Of course, this requires significant investment in teacher training, which means governments must commit meaningful resources to education reform.',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Is it possible for individuals to make a meaningful difference to global problems like climate change, or is this the responsibility of governments and corporations?',
            hint: 'Câu hỏi về tác nhân thay đổi (agency). Lập luận đa chiều: cá nhân có ảnh hưởng giới hạn nhưng hành động tập thể có sức mạnh lớn. Tránh thái độ bi quan hoặc quá lạc quan.',
            samplePhrases: [
              'This is a question I find genuinely complex. On one level, the structural scale of climate change clearly requires systemic solutions at the government and corporate level.',
              'However, I would caution against dismissing individual action entirely. Consumer choices do drive market behaviour, and social movements have historically shifted policy.',
              'The key tension is that individual action can sometimes become a substitute for demanding systemic change — a kind of moral offloading.',
              'My view is that individuals should act responsibly while simultaneously holding institutions accountable, because neither alone is sufficient.',
            ],
          },
          {
            type: 'speaking',
            prompt: 'Some people think that preserving cultural traditions is less important than adapting to modern life. How far do you agree?',
            hint: 'Câu hỏi văn hoá vs hiện đại hoá. Phân biệt giữa "bảo tồn" (preserve) và "fossilize" (đóng băng). Lập luận rằng văn hoá sống động phải tiến hoá, không biến mất.',
            samplePhrases: [
              'I think this is a false dichotomy — cultural traditions and modernity are not necessarily in conflict.',
              'Living cultures have always evolved and adapted; the question is whether that change is driven internally or imposed externally.',
              'What I would oppose is the wholesale abandonment of cultural identity in pursuit of a homogenised global monoculture.',
              'A healthy society, in my view, is one that can selectively preserve what is meaningful while being open to change that improves people\'s lives.',
            ],
          },
        ] as LessonCard[],
      },
    ],
  },
]

// ─── Helper functions ────────────────────────────────────────────────────────

export function getAllLessons(): LessonData[] {
  return STAGES.flatMap(stage => stage.lessons)
}

export function getLessonById(id: string): LessonData | undefined {
  return getAllLessons().find(l => l.id === id)
}

export function getStageByLessonId(id: string): StageData | undefined {
  return STAGES.find(stage => stage.lessons.some(l => l.id === id))
}
